### ISSUE TITLE
[Security Issue][BUG]Missing rate limiting

### ISSUE THREAD

**Issue by omarhany0** [asim97/SecureCodingDojo_DEBI#13]
**Describe the Security issue **
HTTP request handlers should not perform expensive operations such as accessing the file system, executing an operating system command or interacting with a database without limiting the rate at which requests are accepted. Otherwise, the application becomes vulnerable to denial-of-service attacks where an attacker can cause the application to crash or become unresponsive by issuing a large number of requests at the same time.

**Location of the issue**
Path :trainingportal/server.js
File  :server.js
Line :224

**Part of the code issue**

```js script

app.get("/public/badge/:code/image.png",async(req,res) => {
This route handler performs , but is not rate-limited.
CodeQL
  var code = req.params.code;
  
  if(util.isNullOrUndefined(code)){

```

**Recommendation**

A rate-limiting middleware should be used to prevent such attacks.

**example to this issue**

```js script

var express = require('express');
var app = express();

app.get('/:path', function(req, res) {
  let path = req.params.path;
  if (isValidPath(path))
    res.sendFile(path);
});

```

**example to solve this issue**

```js script
var express = require('express');
var app = express();

// set up rate limiter: maximum of five requests per minute
var RateLimit = require('express-rate-limit');
var limiter = new RateLimit({
  windowMs: 1*60*1000, // 1 minute
  max: 5
});

// apply rate limiter to all requests
app.use(limiter);

app.get('/:path', function(req, res) {
  let path = req.params.path;
  if (isValidPath(path))
    res.sendFile(path);
});

```

**References**
OWASP: Denial of Service Cheat Sheet.
Wikipedia: Denial-of-service attack.
NPM: express-rate-limit.
Common Weakness Enumeration: CWE-770.
Common Weakness Enumeration: CWE-307.
Common Weakness Enumeration: CWE-400.

**Comment by asim97** [comment]
this is a very similar to issue #17
