### ISSUE TITLE
[Security Issue][BUG]Reflected cross-site scripting

### ISSUE THREAD

**Issue by omarhany0** [asim97/SecureCodingDojo_DEBI#14]
**Describe the Security issue **
Directly writing user input (for example, an HTTP request parameter) to an HTTP response without properly sanitizing the input first, allows for a cross-site scripting vulnerability.

This kind of vulnerability is also called reflected cross-site scripting, to distinguish it from other types of cross-site scripting.

**Location of the issue**
Path :trainingportal/server.js
File  :server.js
Line :220

**Part of the code issue**

```js script
let html = badgeHtml;
html = html.replace(/BADGE_IMG_SRC/g, imgSrc);
html = html.replace("BADGE_URL", config.dojoUrl+req.url);
res.send(html);

```

**Recommendation**

To guard against cross-site scripting, consider using contextual output encoding/escaping before writing user input to the response, or one of the other solutions that are mentioned in the references.

**example to this issue**

```js script

var app = require('express')();

app.get('/user/:id', function(req, res) {
  if (!isValidUserId(req.params.id))
    // BAD: a request parameter is incorporated without validation into the response
    res.send("Unknown user: " + req.params.id);
  else
    // TODO: do something exciting
    ;
});
```

**example to solve this issue**

```js script
var escape = require('escape-html');

var app = require('express')();

app.get('/user/:id', function(req, res) {
  if (!isValidUserId(req.params.id))
    // GOOD: request parameter is sanitized before incorporating it into the response
    res.send("Unknown user: " + escape(req.params.id));
  else
    // TODO: do something exciting
    ;
});

```

**References**
OWASP: XSS (Cross Site Scripting) Prevention Cheat Sheet.
OWASP Types of Cross-Site Scripting.
Wikipedia: Cross-site scripting.
Common Weakness Enumeration: CWE-79.
Common Weakness Enumeration: CWE-116.

**Comment by asim97** [comment]
after examing this part, we found that if there is any modification in the (req.url) we case a server error response only
so, will close this issue with a false alert.
