### ISSUE TITLE
[Security Issue][BUG]Uncontrolled data used in path expression

### ISSUE THREAD

**Issue by omarhany0** [asim97/SecureCodingDojo_DEBI#16]
**Describe the Security issue **
Accessing files using paths constructed from user-controlled data can allow an attacker to access unexpected resources. This can result in sensitive information being revealed or deleted, or an attacker being able to influence behavior by modifying unexpected files.

**Location of the issue**
Path :trainingportal/challenges.js
File  :challenges.js
Line :60

**Part of the code issue**

```js script
function getDefinifionsForModule(moduleId){
    var defs = Object.freeze(require(path.join(__dirname, getModulePath(moduleId), '/definitions.json')));

```

**Recommendation**
Validate user input before using it to construct a file path, either using an off-the-shelf library like the sanitize-filename npm package, or by performing custom validation.

Ideally, follow these rules:

Do not allow more than a single "." character.
Do not allow directory separators such as "/" or "\" (depending on the file system).
Do not rely on simply replacing problematic sequences such as "../". For example, after applying this filter to ".../...//", the resulting string would still be "../".
Use a whitelist of known good patterns.

**example to this issue**

```js script
var fs = require('fs'),
    http = require('http'),
    url = require('url');

var server = http.createServer(function(req, res) {
  let path = url.parse(req.url, true).query.path;

  // BAD: This could read any file on the file system
  res.write(fs.readFileSync(path));

  // BAD: This could still read any file on the file system
  res.write(fs.readFileSync("/home/user/" + path));
});

```

**References**
OWASP: Path Traversal.
npm: sanitize-filename package.
Common Weakness Enumeration: CWE-22.
Common Weakness Enumeration: CWE-23.
Common Weakness Enumeration: CWE-36.
Common Weakness Enumeration: CWE-73.
Common Weakness Enumeration: CWE-99.

**Comment by asim97** [comment]
Thanks Omar, after examing the code very well.
this is a false bug as the (moduleId) variable isn't provided by the user ... this variable is loaded into the system from a different file called difinations.json ==> location "traningportal/static/lessons/blackBelt"
