### ISSUE TITLE
Registration Bug

### ISSUE THREAD

**Issue by MohamedAboHelal** [asim97/SecureCodingDojo_DEBI#25]
**Describe the bug**
After submitting your information in registration page, your information keep existing in the page.

**Expected behavior**
I think you should clear all these information after user hitting submit button

**Screenshots**
![process_after_registeration](https://user-images.githubusercontent.com/42704527/124379541-028fbe00-dcb8-11eb-81dc-a9d452f8c7cb.PNG)

**Comment by asim97** [comment]
this is related to your web browser... this feature is called (autofill)
It save the submitted inputs to use it again within the same website
