### ISSUE TITLE
Unsecure HTTP (instead of HTTPS)

### ISSUE THREAD

**Issue by MohamedZidan097** [asim97/SecureCodingDojo_DEBI#26]
the website has been deployed on port 80 which uses http protocol and that is not secure because the traffic in this case is sent as a plain text and attacker  can capture the credential easily during login process by sniffing the connection. 
Instead of that the website should have been deployed on port 443 https protocol , which is considered secure because  it encrypts the traffic .
![http](https://user-images.githubusercontent.com/61326628/124379806-6666b680-dcb9-11eb-9c1d-915b5bce643c.JPG)
![capfile](https://user-images.githubusercontent.com/61326628/124379810-69fa3d80-dcb9-11eb-8310-3c2b5d082e25.JPG)

**Comment by asim97** [comment]
We are going to get ssl certificate and get a new domin for  the server

**Comment by asim97** [comment]
converting to HTTPS is now in progress

**Comment by asim97** [comment]
This major security issue fixed in the following commit => 5a56e2c86eb3e01250d845bfc0a328cbde3ee344
Thanks for testing @MohamedAboHelal
