### ISSUE TITLE
Error in the challenges solving

### ISSUE THREAD

**Issue by MohamedZidan097** [asim97/SecureCodingDojo_DEBI#29]
error in solve challenge if maximum  belt higher than my current belt

![error](https://user-images.githubusercontent.com/61326628/124390951-59b08580-dcee-11eb-9bf3-0d3fc27088e7.png)
![error1](https://user-images.githubusercontent.com/61326628/124390952-5a491c00-dcee-11eb-8679-eec9ae87615d.png)

**Comment by asim97** [comment]
fixed in the follwing commit => 18d6c9027837598a2949b0aae99fcf755b5e23fd
thanks Zidan
